# Dataframe Com Pandas

# Aula 3 - Estrutura Principal: DataFrame

Nesta aula vamos aprender:

- O que é um DataFrame
- Como criar um DataFrame
- Como visualizar seus dados
- Como utilizar:
    - head()
    - tail()
    - info()
    - describe()

In [1]:
import pandas as pd

In [12]:
dados = {
    "ID": list(range(1, 51)),
    "Produto": [
        "Notebook","Mouse","Teclado","Monitor","Cadeira","Mesa","Impressora","Headset","Webcam","SSD"
    ] * 5,
    "Categoria": [
        "Informática","Informática","Informática","Informática","Móveis",
        "Móveis","Informática","Informática","Informática","Informática"
    ] * 5,
    "Preco": [
        3500,80,150,1200,850,1200,900,250,180,320,
        3800,75,170,1350,900,1300,950,280,200,350,
        3600,90,160,1250,870,1280,920,260,190,340,
        3700,85,175,1400,920,1350,980,300,210,360,
        3900,95,180,1450,950,1400,1000,320,220,380
    ],
    "Quantidade": [
        2,10,5,3,4,2,1,8,6,7,
        1,15,4,2,3,2,1,6,5,8,
        2,12,6,3,4,2,1,7,6,5,
        1,14,3,2,2,1,1,5,4,6,
        1,10,5,2,3,1,1,4,3,5
    ]
}

df = pd.DataFrame(dados)

df

    ID     Produto    Categoria  Preco  Quantidade
0    1    Notebook  Informática   3500           2
1    2       Mouse  Informática     80          10
2    3     Teclado  Informática    150           5
3    4     Monitor  Informática   1200           3
4    5     Cadeira       Móveis    850           4
5    6        Mesa       Móveis   1200           2
6    7  Impressora  Informática    900           1
7    8     Headset  Informática    250           8
8    9      Webcam  Informática    180           6
9   10         SSD  Informática    320           7
10  11    Notebook  Informática   3800           1
11  12       Mouse  Informática     75          15
12  13     Teclado  Informática    170           4
13  14     Monitor  Informática   1350           2
14  15     Cadeira       Móveis    900           3
15  16        Mesa       Móveis   1300           2
16  17  Impressora  Informática    950           1
17  18     Headset  Informática    280           6
18  19      Webcam  Informática    200           5
19  20         SSD  Informática    350           8
20  21    Notebook  Informática   3600           2
21  22       Mouse  Informática     90          12
22  23     Teclado  Informática    160           6
23  24     Monitor  Informática   1250           3
24  25     Cadeira       Móveis    870           4
25  26        Mesa       Móveis   1280           2
26  27  Impressora  Informática    920           1
27  28     Headset  Informática    260           7
28  29      Webcam  Informática    190           6
29  30         SSD  Informática    340           5
30  31    Notebook  Informática   3700           1
31  32       Mouse  Informática     85          14
32  33     Teclado  Informática    175           3
33  34     Monitor  Informática   1400           2
34  35     Cadeira       Móveis    920           2
35  36        Mesa       Móveis   1350           1
36  37  Impressora  Informática    980           1
37  38     Headset  Informática    300           5
38  39      Webcam  Informática    210           4
39  40         SSD  Informática    360           6
40  41    Notebook  Informática   3900           1
41  42       Mouse  Informática     95          10
42  43     Teclado  Informática    180           5
43  44     Monitor  Informática   1450           2
44  45     Cadeira       Móveis    950           3
45  46        Mesa       Móveis   1400           1
46  47  Impressora  Informática   1000           1
47  48     Headset  Informática    320           4
48  49      Webcam  Informática    220           3
49  50         SSD  Informática    380           5

# Método head()

O método head() mostra as primeiras linhas do DataFrame.

É útil quando estamos trabalhando com tabelas muito grandes e queremos visualizar apenas uma amostra inicial.

ou se quiser ver as primeiras 10 linhas - df.head(10)

In [16]:
df.head(15)

    ID     Produto    Categoria  Preco  Quantidade
0    1    Notebook  Informática   3500           2
1    2       Mouse  Informática     80          10
2    3     Teclado  Informática    150           5
3    4     Monitor  Informática   1200           3
4    5     Cadeira       Móveis    850           4
5    6        Mesa       Móveis   1200           2
6    7  Impressora  Informática    900           1
7    8     Headset  Informática    250           8
8    9      Webcam  Informática    180           6
9   10         SSD  Informática    320           7
10  11    Notebook  Informática   3800           1
11  12       Mouse  Informática     75          15
12  13     Teclado  Informática    170           4
13  14     Monitor  Informática   1350           2
14  15     Cadeira       Móveis    900           3

# Método tail()

O método tail() mostra as últimas linhas do DataFrame.

In [19]:
df.tail(15)

    ID     Produto    Categoria  Preco  Quantidade
35  36        Mesa       Móveis   1350           1
36  37  Impressora  Informática    980           1
37  38     Headset  Informática    300           5
38  39      Webcam  Informática    210           4
39  40         SSD  Informática    360           6
40  41    Notebook  Informática   3900           1
41  42       Mouse  Informática     95          10
42  43     Teclado  Informática    180           5
43  44     Monitor  Informática   1450           2
44  45     Cadeira       Móveis    950           3
45  46        Mesa       Móveis   1400           1
46  47  Impressora  Informática   1000           1
47  48     Headset  Informática    320           4
48  49      Webcam  Informática    220           3
49  50         SSD  Informática    380           5

# Método info()

O método info() exibe informações gerais sobre o DataFrame.

Podemos visualizar:

- Quantidade de linhas
- Quantidade de colunas
- Tipos de dados
- Valores não nulos

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          50 non-null     int64
 1   Produto     50 non-null     str
 2   Categoria   50 non-null     str
 3   Preco       50 non-null     int64
 4   Quantidade  50 non-null     int64
dtypes: int64(3), str(2)
memory usage: 2.1 KB

# Método describe()

O método describe() gera estatísticas descritivas para as colunas numéricas.

In [21]:
df.describe()

             ID        Preco  Quantidade
count  50.00000    50.000000   50.000000
mean   25.50000   926.800000    4.340000
std    14.57738  1039.926293    3.378262
min     1.00000    75.000000    1.000000
25%    13.25000   202.500000    2.000000
50%    25.50000   615.000000    3.500000
75%    37.75000  1237.500000    6.000000
max    50.00000  3900.000000   15.000000

## Entendendo o resultado

count → quantidade de registros

mean → média dos valores

std → desvio padrão

min → menor valor

25% → primeiro quartil

50% → mediana

75% → terceiro quartil

max → maior valor

In [22]:
df["Preco"].describe()

# Agora estamos analisando apenas a coluna Preco.
# Isso é útil quando queremos estudar uma variável específica.

count      50.000000
mean      926.800000
std      1039.926293
min        75.000000
25%       202.500000
50%       615.000000
75%      1237.500000
max      3900.000000
Name: Preco, dtype: float64

In [23]:
df["Quantidade"].describe()

count    50.000000
mean      4.340000
std       3.378262
min       1.000000
25%       2.000000
50%       3.500000
75%       6.000000
max      15.000000
Name: Quantidade, dtype: float64

# Resumo da Aula

Aprendemos:

✅ O que é um DataFrame

✅ Como criar um DataFrame

✅ Como visualizar dados

✅ Como usar:
- head()
- tail()
- info()
- describe()

Esses métodos são os primeiros passos para explorar qualquer conjunto de dados em Ciência de Dados.